### ISSUE TITLE
Error in das-cli update-version

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-toolbox#130]
![Image](https://github.com/user-attachments/assets/443686e2-a49b-4b11-8c14-f641713f752d)

**Comment by levisingularity** [comment]
@andre-senna ![Image](https://github.com/user-attachments/assets/b8714fa8-1f57-4e55-b97d-c141892c9403)

I suppose this issue was already fixed in one of the previous updates. I couldn´t reproduce this error.

**Comment by andre-senna** [comment]
Recent fixes wouldn't affect the behavior of a previous (0.4.4) version.

**Comment by levisingularity** [comment]
@andre-senna, I attempted to reproduce this issue and also asked @eddiebrissow to try reproducing it, but neither of us encountered any problems.

![Image](https://github.com/user-attachments/assets/77454089-2d9a-4598-b70d-3ff5e5dedfef)

**Comment by andre-senna** [comment]
@levisingularity 
OK. You can close the issue for now. Perhaps it's something related to my macOS environment.
